DROP TABLE E_TIPO_PLAZO;
DROP TABLE E_PROCEDIMIENTO;
DROP TABLE E_ESPECIF_PROCEDIMIENTO;
DROP TABLE E_PERSONA_JURIDICA;
DROP TABLE E_PERSONA_NATURAL;
DROP TABLE E_PERSONA;

CREATE TABLE E_PERSONA (ID INTEGER NOT NULL, PRIMARY KEY(ID));

CREATE TABLE E_PERSONA_NATURAL (IDPERSONA INTEGER NOT NULL,
	PRIMER_NOMBRE VARCHAR(40) NOT NULL,
	SEGUNDO_NOMBRE VARCHAR(40) NULL,
	PRIMER_APELLIDO VARCHAR(60) NOT NULL,
	SEGUNDO_APELLIDO VARCHAR(60) NULL,
	PRIMARY KEY(IDPERSONA));

ALTER TABLE E_PERSONA_NATURAL 
  ADD CONSTRAINT  FK_PERSONANATURAL_PERSONA
    FOREIGN KEY (IDPERSONA) REFERENCES E_PERSONA (ID);

CREATE TABLE E_PERSONA_JURIDICA(IDPERSONA INTEGER NOT NULL,
	RAZON_SOCIAL VARCHAR(60) NOT NULL,
	NOMBRE_COMERCIAL VARCHAR(60) NULL,
  PRIMARY KEY(IDPERSONA));

ALTER TABLE E_PERSONA_JURIDICA 
  ADD CONSTRAINT FK_PERSONAJURIDICA_PERSONA
  FOREIGN KEY (IDPERSONA) REFERENCES E_PERSONA (ID);

CREATE TABLE E_PROCEDIMIENTO (ID INTEGER NOT NULL,
  NOMBRE  VARCHAR(80) NOT NULL,
  DESCRIPCION VARCHAR(200) NULL,
  PRIMARY KEY(ID));

CREATE TABLE E_ESPECIF_PROCEDIMIENTO(IDPROCEDIMIENTO INTEGER,
  IDESPECIFICACION INTEGER NOT NULL,
  VALIDODESDE DATE NOT NULL,

  TIENE_EVALUACION_LEGAL INTEGER NOT NULL,
  TIENE_EVALUACION_FINANCIERA INTEGER NOT NULL,
  TIENE_EVALUACION_TECNICA INTEGER NOT NULL,
  DERECHO_TRAMITACION FLOAT NOT NULL,
  VALIDOHASTA DATE NULL,
  PRIMARY KEY(IDPROCEDIMIENTO, IDESPECIFICACION, VALIDODESDE));

ALTER TABLE E_ESPECIF_PROCEDIMIENTO
  ADD CONSTRAINT E_ESPECIFPROCED_FK_PROC
  FOREIGN KEY (IDPROCEDIMIENTO) REFERENCES E_PROCEDIMIENTO(ID);

CREATE TABLE E_TIPO_PLAZO (ID INTEGER NOT NULL,
  NOMBRE  VARCHAR(30) NOT NULL,
  PRIMARY KEY (ID));

CREATE TABLE R_PLAZO_PROCEDIMIENTO(
  IDPROCEDIMIENTO INTEGER NOT NULL,
  IDESPECIFICACION INTEGER NOT NULL,
  IDTIPOPLAZO INTEGER NOT NULL,
  VALIDODESDE DATE NOT NULL,
  VALIDOHASTA DATE NULL,
  DIAS INTEGER NOT NULL,
  PRIMARY KEY(IDPROCEDIMIENTO,IDESPECIFICACION,IDTIPOPLAZO,VALIDODESDE));
    
ALTER TABLE R_PLAZO_PROCEDIMIENTO
  ADD CONSTRAINT E_ESPECIF_PROCED_FK_TIPO
  FOREIGN KEY (IDTIPOPLAZO) REFERENCES E_TIPO_PLAZO(ID);
  